name: Build and Deploy Docker Image to GCR

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
 #   environment: dev
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Google Cloud SDK
        run: |
          curl https://sdk.cloud.google.com > install.sh
          bash install.sh --disable-prompts

      - name: Configure Docker authentication
        run: |
          echo ${{ secrets.GCP_SA_KEY }} | base64 --decode > key.json
          gcloud auth activate-service-account --key-file=key.json
          gcloud auth configure-docker gcr.io

  #    - name: Set up JDK 11
  #      run: |
  #        sudo apt-get update
  #        sudo apt-get install -y openjdk-11-jdk

  #    - name: Build with Gradle
  #      run: ./gradlew build

      - name: Install Docker
        run: |
          sudo apt-get update
          sudo apt-get install -y apt-transport-https ca-certificates curl gnupg lsb-release
          curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo gpg --dearmor -o /usr/share/keyrings/docker-archive-keyring.gpg
          echo "deb [arch=amd64 signed-by=/usr/share/keyrings/docker-archive-keyring.gpg] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable" | sudo tee /etc/apt/sources.list.d/docker.list > /dev/null
          sudo apt-get update
          sudo apt-get install -y docker-ce docker-ce-cli containerd.io

      - name: Build Docker image
        run: |
          IMAGE_TAG=$(git rev-parse --short HEAD)
          docker build -t gcr.io/durable-catbird-340811/sample:$IMAGE_TAG .

      - name: Push Docker image to GCR
        run: |
          IMAGE_TAG=$(git rev-parse --short HEAD)
          docker push gcr.io/durable-catbird-340811/sample:$IMAGE_TAG

 #     - name: Deploy Docker image to Cloud Run
 #       run: |
 #         IMAGE_TAG=$(git rev-parse --short HEAD)
 #         gcloud run deploy sample --image gcr.io/durable-catbird-340811/sample:$IMAGE_TAG --platform managed --region us-central1 --allow-unauthenticated --project durable-catbird-340811

  deployDev:
    name: Deploy to Dev
    permissions:
      contents: none
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: "dev"
 #     url: ${ { steps.deploy-to-webapp.outputs.webapp-url } }

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Google Cloud SDK
        run: |
          curl https://sdk.cloud.google.com > install.sh
          bash install.sh --disable-prompts
          echo ${{ secrets.GCP_SA_KEY }} | base64 --decode > key.json
          gcloud auth activate-service-account --key-file=key.json

      - name: Deploy Docker image to Cloud Run
        run: |
          IMAGE_TAG=$(git rev-parse --short HEAD)
          gcloud run deploy sample --image gcr.io/durable-catbird-340811/sample:$IMAGE_TAG --platform managed --region us-central1 --allow-unauthenticated --project durable-catbird-340811

  deployprod:
    name: Deploy to Prod
    permissions:
      contents: none
    runs-on: ubuntu-latest
    needs: deployDev
    environment:
      name: "production"
 #     url: ${ { steps.deploy-to-webapp.outputs.webapp-url } }

    steps:    
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Google Cloud SDK
        run: |
          curl https://sdk.cloud.google.com > install.sh
          bash install.sh --disable-prompts
          echo ${{ secrets.GCP_SA_KEY }} | base64 --decode > key.json
          gcloud auth activate-service-account --key-file=key.json

      - name: Deploy Docker image to Cloud Run
        run: |
          IMAGE_TAG=$(git rev-parse --short HEAD)
          gcloud run deploy sample-prod --image gcr.io/durable-catbird-340811/sample:$IMAGE_TAG --platform managed --region us-central1 --allow-unauthenticated --project durable-catbird-340811
